### ISSUE TITLE
Issue with search asm

### ISSUE THREAD

**Issue by StevenD33** [AetherBlack/utils#1]
Hi, when i  search with search_asm.py `repne` it crash 

here is the log error 
```
Description :
-------------
Repeats until ecx = 0 or ZF = 1.


Traceback (most recent call last):
  File "/usr/local/bin/search_asm.py", line 109, in <module>
    asm.get_content("Examples", "Comments")
  File "/usr/local/bin/search_asm.py", line 36, in get_content
    while self.text_list[index] != stop_value and self.text_list[index] != next_title:
IndexError: list index out of range

```

**Comment by AetherBlack** [comment]
Hi,

It's patch in https://github.com/AetherBlack/utils/commit/851f93a604a5bd1523a36cf2047c970def3efe9d

Thanks for the issue.
